/* ================= v93: Ask the terminal, example questions grouped into theme tiles =================
   A new "Examples by theme" panel above the existing numbered list (which stays as it was). Each tile names a theme, says in one line
   what that kind of question does and which words drive it, and lists examples with Run (ask it now) and Edit (put it in the box to
   change it). Nothing else changes. */
(function(){
try{
var box=$("#qmEx20"), inp=$("#qmInput"); if(!box||!inp||$("#hx93Tiles")) return;
function hE(s){ return String(s).replace(/[&<>"]/g,function(c){ return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]; }); }
var T=[
 {t:"Screens: find names",d:"Filters plus a ranking. Words: least/most volatile, highest anomaly, strength, uptrend, in a sector or subsector, excluding.",h:"",q:[
  "Which are the 10 least volatile symbols in rising subsectors?","Show 10 stocks with volatility below 30 in Healthcare","Give me 8 quiet stocks in an established uptrend, max 2 per sector, excluding Energy.","Show 10 independent stocks with strong momentum.","Show 10 liquid stocks in an uptrend with low volatility.","Show 10 oversold stocks in a downtrend."]},
 {t:"Trend concepts",d:"Plain-English setups turned into rules: strong and improving, recovering, rolling over, breaking out, not extended, healthy or steady uptrend.",q:[
  "Show 10 strong and improving stocks that are not extended.","Show 10 recovering stocks with the lowest volatility.","Show 10 stocks rolling over in Financials.","Show 10 momentum leaders in a fresh uptrend.","Which 10 stocks are extended and fading?","Give me 10 stocks with a steady uptrend of at least 30 sessions, sorted by trend length."]},
 {t:"Portfolios by risk level",d:"Conservative, moderate or aggressive sets volatility and extension limits; add caps (max 2 per sector), long short, amount to invest.",q:[
  "Build a conservative 10 stock portfolio of strong and improving stocks.","Build a moderate 12 stock portfolio of healthy uptrends, max 2 per sector.","Build an aggressive 8 stock portfolio of stocks breaking out.","Show the risk spectrum with 5 steady uptrend stocks each.","Build a 10 stock long short portfolio, conservative, invest 100k.","Build a conservative 10 stock portfolio with a 12 month return above 10%"]},
 {t:"Diversified portfolios",d:"Keep names from moving together: add “with low correlation between them” or “correlation below 0.3 between them”, or cap per sector or subsector.",q:[
  "Build a moderate 10 stock portfolio of healthy uptrends with low correlation between them","Build a conservative 8 stock portfolio of strong and improving stocks with correlation below 0.3 between them","Build a 10 stock portfolio from the calmest subsectors, fresh uptrend, above cluster one, no sector limit.","Which stocks are least correlated with the market?","Average correlation of these"]},
 {t:"Sectors and subsectors",d:"Group-level reads: rising or falling subsectors, mean scores, compare two sectors, counts by sector.",q:[
  "Which 10 subsectors have the highest mean anomaly?","Compare Energy and Materials.","Which 5 sectors have the highest mean 1D return?","How many stocks are in an uptrend by subsector?","How many stocks are rolling over, by sector?","Show 10 stocks leading their sector with low volatility."]},
 {t:"Long-horizon history (part E)",d:"Needs the price history: YTD, 1 to 12 month returns, drawdown, volatility, beta and correlation to RSP, distance from the 52-week high.",q:[
  "Stocks in an uptrend with YTD return above 20% and 12M drawdown better than -15%.","Which 10 stocks have the highest 12 month return?","stocks within 5% of their 52 week high","lowest beta stocks","best 3 month performers in Healthcare","YTD losers"]},
 {t:"Diagnostics and follow-ups",d:"Say “these” to work on the previous answer: diagnostic, pair test, correlation, which of these …",q:[
  "Give me a diagnostic of MGM LVS WYNN","diagnostic of NDSN ITW IEX AME","Give me a diagnostic of these","which of these are in an uptrend","How correlated are these?","Pair test these"]},
 {t:"Specific names",d:"One ticker at a time: its story, neighbours, returns, group, cohort and cluster.",q:[
  "Tell me about NVDA","What are the symbols around AAPL?","what is the year to date return of NDSN","which hidden group is NVDA in","which cohort is AAPL in","Which cluster is AMAT in?"]},
 {t:"Advancing and declining",d:"Direction words: rising or falling subsectors, accelerating or decelerating, improving or deteriorating, breaking out or down.",q:[
  "Show 10 accelerating stocks that are above cluster one.","Show 10 decelerating stocks in rising subsectors.","Show 10 weak and falling stocks with a larger anomaly.","Show 10 stocks breaking down with high volatility.","How many stocks are recovering, by subsector?","Show 10 stocks lagging their sector that are accelerating."]},
 {t:"Combined questions",d:"Stack any of the above in one sentence: concept + risk + sector + history + caps + correlation.",q:[
  "Show 10 strong and improving stocks in rising subsectors with a YTD return above 10% and low volatility","Build a conservative 10 stock portfolio of healthy uptrends in Healthcare and Industrials, max 2 per subsector","Build an aggressive 8 stock portfolio of momentum leaders, excluding Energy","Show 10 recovering stocks above cluster one with a larger anomaly","Which Industrials stocks are connected to Financials and improving?","Top 10 subsector pairs with the most tickers connected and above cluster 1","Build a 10 stock portfolio of uptrends with 12 month drawdown better than -25% and low correlation between them","Build an aggressive 10 stock portfolio with a YTD return above 10% and low correlation between them"]},
 {t:"Correlation numbers and matrices",d:"Numbers straight from the correlation matrices: a pair, a matrix of names, ranked pairs in a group, two sectors.",q:[
  "What is the correlation between NVDA and AMD?","Correlation matrix of XOM CVX COP SLB EOG","How correlated are MGM LVS WYNN?","Most correlated pairs in Semiconductors","Least correlated pairs in Energy","Most correlated pairs across sectors","What is the correlation between Energy and Utilities?"]},
 {t:"Hierarchical clusters map",d:"Alex-style blocks from the clustered matrix: rising or falling together, a name's block, blocks that cross sectors, other windows.",q:[
  "Which clusters are rising together?","Falling blocks YTD","Which cluster is AMAT in?","Which clusters cross sectors?","Hierarchical clusters over 252 bars","Which blocks are falling together over 60 bars?","Which clusters are falling together in Financials?","Which cluster is MU in over 60 bars?","Build a portfolio from the strongest name in each rising block over 126 bars","Plot the rising blocks YTD","Diagnostic of the falling blocks over 252 bars"]},
 {t:"Price relationships",d:"What moves with what: partners, hedges, stocks that trade like another sector, relationships breaking down or forming.",q:[
  "What moves with NVDA?","Hedges for NVDA in other sectors","Which stocks trade like another sector?","Which relationships are breaking down?","Which relationships are forming across sectors?","What is NVDA decoupling from?"]},
 {t:"Pairs trading",d:"Cointegration both ways, beta stability, half-life, spread z-score and a verdict, for two names, a list or a whole group.",q:[
  "Pair test MGM LVS","Is LVS WYNN an eligible pairs trade?","Pair test MGM LVS WYNN","Top 5 pairs trades in Energy","Best pairs trades in Semiconductors","Pair test these","Best pairs trades in Banks - Regional","Top 5 pairs trades in Utilities","Pair test XOM CVX"]},
 {t:"Hidden groups, links and lead-lag",d:"Connections the sector labels hide: neighbours in other sectors, hidden groups, cohorts, price groups, what tends to move first.",q:[
  "Which stocks have neighbours in other sectors?","show hidden groups that cross sectors","How is NVDA connected to other sectors?","Which subsectors in different sectors move alike?","Price groups that cross sectors","What leads Semiconductors?"]},
 {t:"Charts: prices and returns",d:"Say plot, chart or draw: prices rebased to 100, return since the start of the window, relative strength against RSP, sector baskets, or the previous answer.",q:[
  "Plot NVDA AMD AVGO","Chart the YTD return of MGM LVS WYNN","Plot the relative strength of NVDA vs RSP","Plot Energy vs Utilities","Plot Energy, Materials and Utilities YTD","Plot these","Plot the YTD return of these","Plot XLE XLU XLK YTD","Chart the relative strength of AMD and AVGO vs RSP over 6 months","Plot IT Sector, Health Care and Financials over 12 months","Plot the relative strength of IT Sector and Financials vs RSP"]},
 {t:"Charts: risk and relationships",d:"Drawdown from the running high, rolling volatility, rolling correlation of two names, and a pair's spread z-score with \u00B12 bands.",q:[
  "Plot the drawdown of MGM LVS over 12 months","Chart the rolling volatility of TSLA and NVDA","Plot the rolling correlation of NVDA and AMD","Plot the rolling correlation of XOM and CVX over 6 months","Plot the spread of OKE TRGP","Plot the drawdown of these","Plot Energy and Utilities drawdown over 12 months","Chart the rolling volatility of Energy vs Utilities","Plot the rolling correlation of Energy and Utilities","Plot the rolling correlation of MU and SNDK YTD","Plot the spread of EOG FANG"]},
 {t:"Portfolios from clusters",d:"Use the hierarchical clusters map to avoid owning the same move twice: one name per cluster, or the best name from each rising block.",q:[
  "Build a moderate 10 stock portfolio of healthy uptrends, one per cluster","Build a conservative 8 stock portfolio of strong and improving stocks, one per cluster","Build a portfolio from the strongest name in each rising block","Build a portfolio from the rising blocks over 252 bars","Build a portfolio from the falling blocks","Which clusters are rising together?","Build an aggressive 8 stock portfolio of momentum leaders, one per cluster","Build a portfolio from the strongest name in each rising block in IT Sector","Build a portfolio from the rising blocks over 60 bars","Build a conservative 10 stock portfolio of strong and improving stocks in rising subsectors, one per cluster"]},
 {t:"Signal convergence",d:"How many of the six Signal convergence lenses flag a name (trend age, structural drift, momentum shape, structure map, anomaly, attention). \u201CSignals converge\u201D = 3 or more.",q:[
  "Show 10 stocks where signals converge","Build a conservative 10 stock portfolio of strong stocks where signals converge","How many stocks have signals converging, by sector?","Show 10 recovering stocks where signals converge","Show 10 stocks with some convergence in rising subsectors","Top 10 most correlated pairs across sectors that share signals","Build a moderate 10 stock portfolio where signals converge, one per cluster","Show 10 stocks where signals converge that are breaking out","How many stocks have signals converging, by subsector?","Show 10 stocks where signals converge in Health Care with low volatility"]},
 {t:"Diagnostics of groups",d:"Diagnostics for a whole sector (with every subsector), a subsector (every name), all sectors, or the previous answer.",q:[
  "Give me diagnostics of Health Care sector and sub sectors","Give me a diagnostic of Energy","Diagnostic of Semiconductors","Diagnostic of Oil & Gas E&P","Diagnostic of all sectors","Give me a diagnostic of these","Diagnostic of Semiconductors and Semiconductor Equipment & Materials","Diagnostic of rising subsectors","Diagnostic of falling subsectors in Financials","Diagnostic of the rising blocks"]},
 {t:"Related pairs, hedges and partners",d:"Pairs that move together and are also linked another way (look-alike, hidden group, cluster, shared signals); hedges and partners for a whole list.",q:[
  "Which two tickers from different sectors have the highest correlation?","Which 6 tickers from different sectors have the highest cross correlation and are also related?","Show 10 strong and improving stocks","Find hedges for these","Find hedges for these in other sectors","What moves most with these?","Top 5 most correlated pairs between Industrials and IT Sector","Most correlated pairs across sectors that are behaviour look-alikes","Which 10 tickers from different sectors have the highest correlation and are in the same hidden group?","Most correlated pairs between Semiconductors and Computer Hardware"]},
 {t:"Cross-sectional: sectors, subsectors and groups",d:"Compare and combine groups: sector against sector, subsectors across sectors, blocks, and portfolios that spread across them.",q:[
  "What is the correlation between Industrials and Materials?","Which sectors move most alike?","Which subsectors in different sectors move most alike?","Diagnostic of Financials and Industrials","Plot the falling blocks","Plot the rolling correlation of Energy and Utilities","Build a conservative 10 stock portfolio of healthy uptrends, max 2 per sector, one per cluster","Top 5 most correlated pairs between Industrials and IT Sector"]},
 {t:"Anomalies",d:"How unusual a name is, on the scan's two readings (graph anomaly, ringed at 0.30, and scan anomaly), with context: sector-confirmed or isolated.",q:[
  "Is PYPL an anomaly?","Is KO an anomaly?","How anomalous are PYPL COF SYF?","Anomaly ranking in Credit Services","Show 10 stocks with the highest graph anomaly","How many stocks have anomaly above 0.3, by sector?","Which anomalies are sector-confirmed?","Show 10 isolated anomalies","Show 10 sector-confirmed stocks with anomaly above 0.3","Which 10 subsectors have the highest mean anomaly?","Top 10 anomaly hidden groups that cross sectors."]},
 {t:"Subsector Web in Ask",d:"Draw the Subsector Web inside the answer for a subsector, a sector or a ticker's subsector; dots open tear sheets, the button opens the interactive tab.",q:[
  "Show me the subsector web for Credit Services","Show the sector web for Energy","Subsector web for NVDA"]},
 {t:"Maps in Ask: relationship, convergence, matrix, hidden groups",d:"Draw a tab's map inside the answer for one ticker, a subsector or a sector (or all): dots open tear sheets, each drawing saves as PNG, a button opens the full tab.",q:[
  "Relationship map of NVDA","Relationship map of Credit Services","Relationship map of Energy","Signal convergence map of Financials","Signal convergence map of Semiconductors","Signal convergence map of PYPL","Correlation matrix of Energy","Correlation matrix of Credit Services","Correlation matrix of Semiconductors over 60 bars","Hidden groups map for Financials","Hidden groups map for COIN","All hidden groups map"]},
 {t:"Charts: scatter, market map, scorecard",d:"Three new charts inside the answer: a quadrant scatter (any two measures, over the grey universe), a sector market map sized by turnover and coloured by any measure, and a colour-coded scorecard of a list. Work on named tickers, \u201Cthese\u201D (the previous answer), a sector, a subsector or the whole market.",q:[
  "Risk return scatter","Risk return scatter of ILMN KEYS WBD BE MET AES COST OXY ORLY","Scatter of 1 month return vs beta for Energy","Scatter of strength vs risk for Semiconductors","Treemap of the market","Market map of Energy coloured by 1 month","Market map of Financials coloured by direction","Scorecard of ILMN KEYS WBD BE MET AES COST OXY ORLY","Compare these","Scorecard of NVDA AMD AVGO MU QCOM"]},
 {t:"Lists and \u201Cthese\u201D: maps, breadth, exit check, exposure, leaderboard",d:"Ask for a list first (or name tickers), then work on it: maps, breadth, re-ranking, an exit check (HOLD / WATCH / EXIT with reasons), sector exposure against the universe, and a relative strength leaderboard against the benchmark.",q:[
  "Show me signal convergence map on ILMN, KEYS, WBD, BE, MET, AES, COST, OXY, ORLY","Relationship map of these","Hidden groups map of these","Correlation matrix of these","Breadth for these","Exit check on these","Exposure of these","Rank these by risk","Relative strength leaderboard of these","Relative strength leaderboard of Energy","Breadth for NVDA AMD AVGO MU QCOM by subsector","Which of these should I exit?"]},
 {t:"Portfolios from a list (adaptive, combined conditions)",d:"Make a list first (the first tile, or any answer), then build from it: the adaptive builder picks from those names only, with your weights, conditions, limits and weighting. Sector limits are off for a list unless you ask (\u201Cmax 2 per sector\u201D). Named tickers work too.",q:[
  "Top 30 stocks by strength","Build a smart portfolio of 8 from these, low correlation, max 2 per sector","Defensive portfolio of 6 from these, ranked by risk, inverse volatility weighted","Smart portfolio of 6 from these, improving, above their trend line, signals converge","Build a portfolio of 5 from these, can be in the same sector, ranked by 3 month return","Smart portfolio of 8 from these, 1 per hidden group, max 1 per subsector","Top 40 stocks by 5 day return","Smart long short portfolio of 3 longs from these","Build a smart momentum portfolio of 5 from NVDA AMD AVGO MU QCOM ANET ARM MRVL LRCX AMAT KLAC, low correlation, weighted"]},
 {t:"Spread and relative strength of a list",d:"Who is stretched against the rest of the list, and who leads inside its own sector: each name against the list's equal-weight basket (z-scores), one name against the basket, and each name against its sector's basket (leaders inside lagging sectors are flagged).",q:[
  "Top 20 stocks in IT Sector by strength","Plot the spread of these","Which of these are stretched?","Spread of NVDA vs these","Relative strength of these vs their sector","Relative strength vs sector for Semiconductors over 6 months","Relative strength of JPM GS MS BAC SCHW WFC vs their sector"]},
 {t:"Rolling correlation: tickers, sectors, subsectors, comparisons",d:"How a name or a group's correlation with the market, its own sector or another ticker has moved over time, with several targets compared on one chart. Pairs keep the pair chart.",q:[
  "Plot the rolling correlation of NVDA","Rolling correlation of NVDA to its sector","Rolling correlation of Energy","Compare the rolling correlation of Energy, Utilities and Financials to RSP","Rolling correlation of Semiconductors vs the market over 6 months","Rolling correlation of AMD AVGO MU to NVDA","Rolling correlation of these to RSP"]},
 {t:"Combined workflows: screen, chart, build, check",d:"Chain the pieces: a normal screen with conditions, then charts of those names, a smart portfolio from them (weights, limits, ranking, weighting), and checks on the result (exit check, exposure, correlation, relative strength). Each answer's names become \u201Cthese\u201D for the next.",q:[
  "Show 10 strong and improving stocks above cluster one","Risk return scatter of these","Market map of these coloured by strength","Scorecard of these","Build a smart portfolio of 6 from these, low correlation, inverse volatility weighted","Exit check on these","Rolling correlation of these to RSP","Show me 20 stocks in a fresh uptrend with low volatility","Relative strength of these vs their sector","Build a defensive portfolio of 5 from these, max 1 per sector","Exposure of these","Show 20 stocks where signals converge","Smart portfolio of 6 from these, improving, max 2 per subsector, ranked by trend strength","Relative strength leaderboard of these","Scatter of strength vs risk for NVDA"]},
 {t:"Query fixes: negations, two-key ranking, group counts",d:"Fixed readings: \u201Cnot in an uptrend\u201D, \u201Cnot overbought\u201D, \u201Cfast above slow\u201D, \u201Cbullish trend flip\u201D, the number after \u201CShow\u201D, \u201Crank by A, then by B\u201D, and counts of two or more conditions per sector or subsector.",q:[
  "Show 15 strong and improving stocks above cluster one","Show 10 stocks not in an uptrend","Show 10 stocks not overbought in an uptrend","Show 10 stocks with fast above slow","Show 10 stocks with a bullish trend flip","Top 10 improving stocks, rank by strength, then by correlation to sector","Which sector has the most improving tickers and the fewest anomalies?","Count number of anomalies per sector, not deteriorating","Which subsectors have the most stocks in an uptrend and above cluster 1?"]},
 {t:"Leaders per group and dual momentum",d:"The best (or lowest) names inside each sector or subsector on any measure, and a dual-momentum baseline: 12-1 month momentum leaders kept only if they beat RSP, otherwise cash.",q:[
  "Top 2 per sector by 5D return","Top 1 per subsector by strength","Lowest 2 per sector by risk","Top 2 per sector by 3 month return","12-1 month momentum leaders beating RSP, else cash","Dual momentum top 8"]},
 {t:"One sentence: screen + chart, columns, exposure",d:"Charts and checks on a screen in one question (the screen runs first), your own columns for any list, and exposure with Hidden Group / price-cluster overlap and five names that would diversify it.",q:[
  "Risk return scatter of strong and improving stocks","Market map of stocks in an uptrend coloured by 1 month","Scorecard of the top 10 improving stocks","Exit check on stocks in a fresh uptrend","Show 3 month return, beta and rank in sector for the top 10 improving stocks","Show trend length and severity for NVDA AMD AVGO","Top 20 stocks by strength","Show trend length, severity and YTD for these","Exposure of these"]},
 {t:"Sentiment and breadth tables",d:"Alex-style colour-coded tables: overall sentiment and one-day breadth, the ETF SEW summary (equity and non-equity), breadth by sector or subsector, and SEW tables of stocks by sector, subsector or direction.",q:[
  "Overall sentiment","Overall sentiment in subsectors","Which subsectors have weak breadth?","ETF SEW summary","Which ETFs are improving? Show the ETF table","Non-equity ETF SEW summary","Sentiment by sector","Breadth by subsector in Financials","SEW summary for Energy","Weakening stocks table in Financials","Strengthening stocks table in Semiconductors","SEW table of improving stocks in Health Care"]},
 {t:"Smart portfolio builder (adaptive)",d:"Your words set the weights (momentum, signal convergence, improving direction, rising subsectors, low volatility), then names are picked one at a time to stay diversified by correlation, sector, subsector, Hidden Group and price cluster. Every pick says why. Works for stocks and ETFs; spelling slips are corrected.",q:[
  "Build a smart 10 stock portfolio: momentum, signal convergence and rising subsectors, diversified across sectors","Build a 12 stock portfolio: momentum leaders, max 2 per sector, low correlation, rising subsectors","Build a defensive smart portfolio of 8 names, low volatility, improving direction, different hidden groups","Build a 10 stock portfolo using hirarichal clusters with low corelation","Give me a diversifed portfolio across sectors where signals converge and subsector is rising","Portfolio of 8 stocks from different hidden groups with strong momentum","Create a long only portfolio of ETFs that are improving","Build a 6 ETF portfolio with low correlation, inverse volatility weighted","Build an aggressive smart portfolio of 10 stocks in the AI infrastructure theme","Best stock in each rising subsector"]},
 {t:"Connections: how things link",d:"How two names, two subsectors, two sectors or two themes are connected: correlation, Hidden Groups, price clusters, look-alikes, shared signal lenses, the strongest correlation path between two names, and the bridge names between two groups.",q:[
  "How is NVDA connected to VST?","How is JPM conected to V","What links Semiconductors and Utilities?","Which stocks bridge IT Sector and Industrials?","What connects Energy and Materials?","Connection between Credit Services and Capital Markets","What links the AI power theme and the semiconductors theme?","Hedge for my portfolio of NVDA, AVGO, MU"]},
 {t:"Themes and rotation",d:"Cross-sector theme baskets (AI and semiconductors, AI power and data centres, software, defensives, rate-sensitive, cyclicals, commodities ...): their strength, members, where money is rotating, leading and lagging groups, and names going against their group.",q:[
  "Which themes are strengthening?","What are the strongest cross sector themes?","Rank all themes by 3 month performance","Show me the AI infrastructure theme","Show me the defensives theme","Is money rotating from growth into defensives?","Where is money rotating this month?","Which subsectors are leading and which are lagging this week?","Which names are strongest in the weakest sectors?","Build a theme portfolio for AI power and data centres"]},
 {t:"Subsector Web, AF Approach",d:"The Subsector Web drawn inside the answer the way Alex draws it (strongest correlation chains, needs the price history), without changing your Subsector Web switch.",q:[
  "Show me the subsector web for Credit Services with AF approach","Show me the subsector web for Semiconductors with AF approach","Show me the subsector web for Banks - Regional with AF approach","Show me the subsector web for Oil & Gas E&P with AF approach"]},
 {t:"Portfolios with conditions (combine them)",d:"Any construction idea (rising blocks, the smart builder, ETFs) plus any mix of conditions: improving, fresh or established uptrend, anomalous, signals converge, not extended, not overbought, liquid, independent of the market, near 52-week highs, beating the market, low drawdown, low beta. The answer lists every condition it applied.",q:[
  "Build a portfolio from the strongest name in each rising block over 126 bars that are improving with signal convergence","Build a portfolio from the strongest name in each rising block YTD that are liquid and not overbought","Build a smart 10 stock portfolio of liquid, not extended stocks in an uptrend near their 52 week highs","Build a smart 8 stock portfolio of independent stocks with low drawdowns, beating the market","Build a smart 10 stock portfolio in an established uptrend with low beta, not deteriorating","Build a smart 8 stock portfolio of anomalous improving stocks with momentum, max 2 per sector","Build a smart 6 ETF portfolio of improving ETFs, inverse volatility weighted","Build a smart 6 ETF portfolio of improving ETFs, inverse volatility weighted and 6 Stocks","Build a portfolio of 4 ETFs and 8 stocks that are improving with signal convergence, low correlation","Build a smart long short portfolio of 6 stocks: longs improving with momentum in rising subsectors","Build an adaptive long/short portfolio of 8 names, low correlation, anomalous","Build a smart long short portfolio of 5 ETFs"]},
 {t:"Sector links with conditions",d:"How a sector's names link to other sectors and subsectors, filtered by direction or anomaly; baskets, bridges and paths between groups. “IT” in these questions means the IT Sector.",q:[
  "Which IT Sector stocks are connected to other sectors and improving?","Which IT Sector stocks are connected to Financials and falling?","Which Industrials stocks are connected to IT Sector and anomalous?","Show me links / connections from different sub sectors to IT","What links Semiconductors and IT?","Which stocks bridge Utilities and IT Sector?","How is NVDA connected to VST?","Which Healthcare stocks are connected to other sectors and anomalous?","What links Credit Services and Software - Infrastructure?"]},
 {t:"Rotation, leaders and laggards",d:"Where money is moving and who goes against their group: rotation between themes, leading and lagging sectors, the best name in each rising subsector or theme, the weakest names in the strongest groups.",q:[
  "Is money rotating from software into semis?","Leading and lagging sectors this month","Which themes are weakening?","Which names are weakest in the strongest subsectors?","Best stock in each rising subsector","Best stock in each theme","Show me the rate-sensitive theme","Which names are strongest in the weakest themes?","Is money rotating from defensives into cyclicals?"]},
 {t:"Ranking, trend lines and bands (fixed)",d:"Your ranking questions that now work: rank by cluster strength (cluster balance), breadth of sector, correlation to sector, trend strength (trend length); above StepMA (its trend line) and the Alex upper / lower rings (bands); short lists say why.",q:["Show me top 10 ranked symbols, above cluster 1, 1 per sector. Rank by cluster strength.", "Show me top 10 ranked symbols, above cluster 1, 1 per sector. Rank by breadth of sector.", "Show me top 10 ranked symbols, above cluster 1, 1 per sector. Rank by correlation to sector.", "Show me top 10 ranked symbols, above cluster 1, 1 per sector, above StepMA Trend.", "Show me top 10 ranked symbols, above cluster 1, 1 per sector, price is at or above StepMA Alex upper ring.", "Show me the trend strength for the top 10 ranked symbols, above cluster 1, 2 per sector.", "Show me top 10 symbols, 1 per sector, not deteriorating, pullback.", "Show me convergence map of KR symbol."]},
 {t:"Ranking combinations (new)",d:"Ten combinations in the same style: trend line, bands, RMESA FIR, cluster balance, sector breadth, correlation to sector, direction, convergence and sector limits together.",q:["Show me top 10 symbols above cluster 1, above StepMA, improving, 1 per sector. Rank by correlation to sector.", "Show me top 10 symbols above band 1, not deteriorating, max 2 per sector.", "Show me top 10 symbols at or below the Alex lower ring, oversold. Rank by strength.", "Show me top 10 symbols above RMESA FIR, above StepMA, 1 per sector. Rank by trend strength.", "Show me top 10 symbols improving, in an uptrend, 1 per sector. Rank by breadth of sector.", "Show me top 10 symbols where signals converge, above cluster 1, 2 per sector. Rank by cluster strength.", "Show me top 10 liquid symbols, not extended, improving, 1 per sector.", "Show me top 10 symbols near their trend line, improving, positive cluster balance, 1 per sector.", "Show me top 10 symbols above StepMA, not deteriorating, where signals converge, 2 per sector.", "Show me top 10 symbols in rising subsectors, above cluster 1, 2 per sector. Rank by 5 day return."]},
 {t:"Rank by wins, adjectives kept",d:"An explicit \u201crank / sort by X\u201d always sets the order (highest or lowest), and words like \u201canomalous\u201d or \u201cliquid\u201d stay as filters; sector-breadth ranking picks each sector's strongest name; weighted portfolios state the exact top-to-bottom ratio.",q:["Show me top 10 anomalous symbols above StepMA, not deteriorating. Rank by strength.", "Show me top 10 liquid symbols improving, sorted by lowest volatility.", "Show me top 10 unusual symbols in an uptrend, 2 per sector. Rank by correlation to sector.", "Show me top 10 symbols improving, 1 per sector. Rank by breadth of sector.", "Build a smart 8 stock portfolio of liquid improving stocks, weighted."]},
 {t:"Trend lines, bands and pullbacks",d:"Near or above the StepMA trend line, the Alex bands (rings), the RMESA FIR line and cluster balance, combined with direction and sector limits. Some return few names on quiet days.",q:["Show me top 10 symbols near their trend line, improving, above cluster 1, 2 per sector.", "Show me top 10 symbols above band 1 in rising subsectors. Rank by trend strength.", "Show me top 10 symbols above StepMA, not extended, positive cluster balance, 1 per sector.", "Show me top 10 symbols above band 1, not deteriorating, 2 per sector.", "Show me top 10 oversold symbols above RMESA FIR. Rank by strength."]},
 {t:"Sector-relative leaders",d:"Rank against the stock's own group: lowest correlation to its sector (independent movers), sector breadth, one per subsector, and 5-day leaders above cluster 1.",q:["Show me top 10 symbols improving, 1 per sector. Rank by lowest correlation to sector.", "Show me top 10 symbols in rising subsectors, 1 per subsector. Rank by strength.", "Show me top 10 symbols where signals converge, 2 per sector. Rank by breadth of sector.", "Show me top 10 liquid symbols above cluster 1, 1 per sector. Rank by 5 day return.", "Show me top 10 symbols not deteriorating, above StepMA, 1 per sector. Rank by lowest correlation to sector."]},
 {t:"Portfolio variants",d:"Smart, mixed ETF + stock and long / short portfolios with conditions: liquid, not extended, low beta, established uptrend, low drawdown, oversold, and risk, score or inverse-volatility weights.",q:["Build a smart 10 stock portfolio of liquid momentum leaders, not extended, max 2 per sector, risk weighted.", "Build a portfolio of 3 ETFs and 7 stocks, improving, low beta, weighted.", "Build a smart 6 stock defensive portfolio, established uptrend, low drawdown, inverse volatility weighted.", "Build a smart long short portfolio of 5 stocks: longs liquid, improving, not extended.", "Build a smart 8 stock portfolio of oversold stocks near their trend line, not deteriorating."]},
 {t:"Next-day setups: signals converging",d:"Names where 3+ of the six lenses agree, stacked with improving direction, fresh uptrends, anomaly, above cluster 1 / StepMA / RMESA FIR, not extended and rising subsectors - the combinations most likely to be in play next session. Research, not a forecast.",q:["Show me top 10 symbols where signals converge, improving, above cluster 1, 1 per sector.", "Show me top 10 symbols where signals converge, in a fresh uptrend, improving.", "Show me top 10 anomalous symbols where signals converge, improving, above StepMA.", "Show me top 10 symbols where signals converge, improving, not extended, 2 per sector. Rank by strength.", "Show me top 10 symbols where signals converge in rising subsectors, above RMESA FIR, 1 per sector."]},
 {t:"Pullback and recovery entries",d:"Better entry points in strong names: near the trend line in rising subsectors or established uptrends, and recovering names above RMESA FIR, with direction and convergence filters.",q:["Show me top 10 symbols near their trend line in rising subsectors, improving, 1 per sector.", "Show me top 10 recovering stocks above RMESA FIR, improving, 1 per sector.", "Show me top 10 symbols in an established uptrend, near their trend line, improving.", "Show me top 10 recovering stocks where signals converge, improving.", "Show me top 10 symbols near their trend line where signals converge, improving."]},
 {t:"High-probability portfolios",d:"Portfolios that stack convergence, improving direction, not extended, rising subsectors, fresh uptrends and anomaly, with diversification and weights; rising-block, long / short and mixed ETF + stock versions.",q:["Build a smart 8 stock portfolio where signals converge, improving, not extended, in rising subsectors, weighted.", "Build a smart 10 stock portfolio of fresh uptrends where signals converge, max 2 per sector, risk weighted.", "Build a smart 8 stock portfolio of anomalous improving stocks where signals converge, low correlation.", "Build a portfolio from the strongest name in each rising block over 60 bars that are improving and not extended.", "Build a smart long short portfolio of 6 stocks: longs where signals converge, improving, not extended.", "Build a portfolio of 3 ETFs and 7 stocks where signals converge, improving, weighted."]},
 {t:"Breakout screens",d:"Names breaking out (a new uptrend of 5 sessions or less, above its trend line), reclaiming cluster 1, above their dominant cluster, touching the upper band, or in a fresh uptrend above cluster 1 and RMESA FIR - with direction, liquidity, not-extended and sector limits, ranked your way.",q:["Show me top 10 stocks breaking out, improving, 1 per sector. Rank by strength.", "Show me top 10 symbols reclaiming cluster 1, not deteriorating.", "Show me top 10 symbols above its dominant cluster, improving, 2 per sector. Rank by trend strength.", "Show me top 10 symbols touching the upper band, improving, 1 per sector. Rank by 5 day return.", "Show me top 10 symbols in a fresh uptrend, above cluster 1, above RMESA FIR, 1 per sector. Rank by strength.", "Show me top 10 stocks breaking out, liquid, not extended. Rank by sector breadth."]},
 {t:"Breakout portfolios",d:"Portfolios built from breakouts: smart (weighted, diversified), with converging signals, long / short, mixed ETF + stock, rising blocks, and fresh uptrends above cluster 1.",q:["Build a smart 10 stock portfolio of stocks breaking out, improving, max 2 per sector, weighted.", "Build a smart long short portfolio of 5 stocks: longs breaking out and improving.", "Build a portfolio of 3 ETFs and 7 stocks breaking out, improving, weighted.", "Build a smart 8 stock portfolio of stocks breaking out where signals converge, weighted.", "Build a portfolio from the strongest name in each rising block YTD that are breaking out.", "Build a smart 8 stock portfolio of fresh uptrends above cluster 1 where signals converge, low correlation."]},
 {t:"Universe listings",d:"Every symbol grouped by sector and subsector (ETFs by fund group), all together or stocks only / ETFs only, optionally with a condition. Tickers open tear sheets; Copy as CSV exports.",q:["show me every symbol in every sector and sub sector.", "Show every stock in every sector and subsector, stocks only", "Show all ETFs by group", "List every symbol in every sector that is improving"]}
];
var el=document.createElement("details"); el.id="hx93Tiles"; el.open=true; el.style.marginTop="10px";
el.innerHTML='<summary style="cursor:pointer;color:var(--accent);font-weight:600">Examples by theme: '+T.length+' themes, '+T.reduce(function(s,x){ return s+x.q.length; },0)+' questions. Run one, or Edit it into your own</summary>'+
  '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(min(330px,100%),1fr));gap:10px;margin-top:10px">'+
  T.map(function(x){ return '<div style="border:1px solid var(--line);border-radius:10px;padding:10px 12px;background:var(--panel)"><div style="font-weight:700;margin-bottom:2px">'+hE(x.t)+'</div><div class="mini" style="margin-bottom:6px;color:var(--ink-2)">'+hE(x.d)+'</div>'+
    x.q.map(function(q){ return '<div style="display:flex;gap:6px;align-items:flex-start;font-size:12.5px;margin:3px 0"><span style="flex:1;color:var(--ink)">'+hE(q)+'</span><button type="button" class="up-link-btn" data-hx93run="'+hE(q)+'">Run</button><button type="button" class="up-link-btn" data-hx93edit="'+hE(q)+'">Edit</button></div>'; }).join("")+'</div>'; }).join("")+'</div>';
box.parentNode.insertBefore(el,box);
el.addEventListener("click",function(e){ var r=e.target.closest?e.target.closest("[data-hx93run],[data-hx93edit]"):null; if(!r) return; e.preventDefault();
  var q=r.getAttribute("data-hx93run")||r.getAttribute("data-hx93edit");
  if(r.hasAttribute("data-hx93run")){ try{ qmSubmit(q); }catch(err){} }
  else { inp.value=q; inp.focus(); try{ inp.setSelectionRange(q.length,q.length); }catch(err){} inp.scrollIntoView({behavior:"smooth",block:"center"}); } });
/* the long numbered list stays, closed by default now that the tiles are above it (click to open) */
try{ box.open=false; }catch(e){}
}catch(e){ try{ console.warn("v93 layer disabled: "+(e&&e.message)); }catch(e2){} }
})();
