const { chromium } = require('playwright'); const fs=require('fs'),path=require('path'),http=require('http');
const srv=http.createServer((q,r)=>{let p=q.url.split('?')[0];if(p=='/')p='/index.html';const f=path.join('site_new',p);if(!fs.existsSync(f)){r.writeHead(404);return r.end();}r.writeHead(200,{'content-type':'text/html'});fs.createReadStream(f).pipe(r);}).listen(0);
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});const pg=await b.newPage();
const errs=[];pg.on('pageerror',e=>errs.push(e.message));
await pg.goto('http://127.0.0.1:'+srv.address().port+'/');await pg.waitForTimeout(800);
const out=await pg.evaluate(()=>{ const E=window.__trk.engine, R=[]; function ok(n,c,x){ R.push((c?"PASS ":"FAIL ")+n+(c?"":" -> "+JSON.stringify(x))); }
 const D=["2026-01-01","2026-01-02","2026-01-05","2026-01-06","2026-01-07","2026-01-08","2026-01-09","2026-01-12"];
 const cl={A:[100,100,100,100,100,110,110,110],B:[100,100,100,100,100,100,100,100],C:[50,50,50,50,50,50,55,60],RSP:[100,100,100,100,100,100,100,110]};
 const hx={dates:D,syms:cl,opens:JSON.parse(JSON.stringify(cl))};
 const p1={settings:{entry:"open",cost:0,notional:100000},ups:[{d:D[1],picks:[{s:"A",side:"long"},{s:"B",side:"long"}],exits:{}},{d:D[4],picks:[{s:"B",side:"long"},{s:"C",side:"long"}],exits:{A:"no longer improving"}}]};
 let r=E(p1,hx,"RSP"); const eq=r.equity[r.equity.length-1];
 ok("1 final value 115500",Math.abs(eq.v-115500)<1e-6,eq.v); ok("1 first fill date is the open after the signal",r.equity[0].d===D[2],r.equity[0].d);
 ok("1 one closed trade A +10% in 3 days",r.trades.length===1&&r.trades[0].s==="A"&&Math.abs(r.trades[0].ret-10)<1e-9&&r.trades[0].days===3&&r.trades[0].inD===D[2]&&r.trades[0].outD===D[5],r.trades);
 ok("1 sell reason kept",r.trades[0].why==="no longer improving",r.trades[0].why);
 ok("1 holdings B 500, C 1050",r.holdings.length===2&&r.holdings.some(h=>h.s==="B"&&Math.abs(h.sh-500)<1e-9)&&r.holdings.some(h=>h.s==="C"&&Math.abs(h.sh-1050)<1e-9),r.holdings);
 ok("1 benchmark +10%",Math.abs(r.stats.bench-10)<1e-9,r.stats.bench); ok("1 return +15.5%",Math.abs(r.stats.ret-15.5)<1e-9,r.stats.ret);
 ok("1 orders buy C, hold B, sell A",r.orders.buy.map(x=>x.s).join()==="C"&&r.orders.hold.map(x=>x.s).join()==="B"&&r.orders.sell.map(x=>x.s).join()==="A",r.orders);
 ok("1 win rate 100%",r.stats.win===100,r.stats.win);
 const p2=JSON.parse(JSON.stringify(p1)); p2.ups.push({d:D[7],picks:[{s:"C",side:"long"}],exits:{B:"x"}}); r=E(p2,hx,"RSP");
 ok("2 update on the last bar is pending",r.pending.length===1&&r.pending[0].n===1,r.pending); ok("2 still 115500 (nothing filled)",Math.abs(r.equity[r.equity.length-1].v-115500)<1e-6,r.equity[r.equity.length-1].v);
 r=E({settings:{entry:"open",cost:0,notional:100000},ups:[{d:D[1],picks:[{s:"A",side:"short"}],exits:{}}]},hx,"RSP");
 ok("3 short A: value 90000 when A rises 10%",Math.abs(r.equity[r.equity.length-1].v-90000)<1e-6,r.equity[r.equity.length-1].v); ok("3 short return -10% on the holding",Math.abs(r.holdings[0].ret+10)<1e-9,r.holdings[0]);
 r=E({settings:{entry:"open",cost:10,notional:100000},ups:[{d:D[1],picks:[{s:"B",side:"long"}],exits:{}}]},hx,"RSP");
 ok("4 costs 10bp: value 100000/1.001",Math.abs(r.equity[r.equity.length-1].v-100000/1.001)<1e-6,r.equity[r.equity.length-1].v);
 r=E(p1,{dates:D,syms:cl},"RSP"); ok("5 no opens: fills at next close with a note",!!r.fillNote&&Math.abs(r.equity[r.equity.length-1].v-115500)<1e-6,[r.fillNote,r.equity[r.equity.length-1].v]);
 const cl2=JSON.parse(JSON.stringify(cl)); cl2.B[6]=null; r=E(p1,{dates:D,syms:cl2,opens:cl},"RSP"); ok("6 missing close carried (no crash, value on that day 108000... )",Math.abs(r.equity[4].v-(2500+50000+1050*55))<1e-6,r.equity[4]);
 r=E({settings:{entry:"close",cost:0,notional:100000},ups:[{d:D[1],picks:[{s:"C",side:"long"}],exits:{}}]},hx,"RSP"); ok("7 close entry fills on the signal day",r.equity[0].d===D[1]&&Math.abs(r.equity[r.equity.length-1].v-120000)<1e-6,[r.equity[0],r.equity[r.equity.length-1]]);
 r=E({settings:{entry:"open",cost:0,notional:100000},ups:[{d:D[1],picks:[{s:"A",side:"long"}],exits:{}},{d:D[3],picks:[],exits:{A:"x"}}]},hx,"RSP"); ok("8 empty update sells everything to cash",r.holdings.length===0&&Math.abs(r.equity[r.equity.length-1].v-100000)<1e-6,[r.holdings,r.equity[r.equity.length-1]]);
 const cl3=JSON.parse(JSON.stringify(cl)); cl3.B[6]=500; r=E(p1,{dates:D,syms:cl3,opens:cl},"RSP"); ok("9 a >40% one-day move is flagged",r.flags.some(f=>/moved/.test(f)),r.flags);
 return R; });
console.log(out.join("\n")); console.log("errors",errs); await b.close(); srv.close(); })();
